apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: app-cicd
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
          grpc:

    exporters:
      logging:
        loglevel: debug
      otlp:
        endpoint: "http://tempo.app-cicd:4317"
        tls:
          insecure: true

    processors:
      batch:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp]
